--insert into Product(title, amount_in_stock, price, year, id) values ('Title', Quantity, Price, Year, 1100);
--insert into Game(platform, developer, genre, rating, pid) values ('Platform', 'Developer', 'Genre', 'ESRB Rating', 1100);
insert into Product(title, amount_in_stock, price, year, id) values ('Assassins Creed', 2, 56.00, 2005, 1101);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Ubisoft Montreal', 'Action-Adventure', 'Mature', 1101);
insert into Product(title, amount_in_stock, price, year, id) values ('BioShock', 5, 34.00, 2007, 1102);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', '2K Boston/2K Australia', 'First-Person Shooter', 'Mature', 1102);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty 2', 4, 52.00, 2002, 1103);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Infinity Ward', 'First-Person Shooter', 'Teen', 1103);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty 3', 4, 44.00, 2001, 1104);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Treyarch', 'First-Person Shooter', 'Teen', 1104);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty 4: Modern Warfare', 1, 64.00, 2000, 1105);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Infinity Ward', 'First-Person Shooter', 'Mature', 1105);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty: World at War', 1, 54.00, 2007, 1106);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Treyarch', 'First-Person Shooter', 'Mature', 1106);
insert into Product(title, amount_in_stock, price, year, id) values ('Crackdown', 5, 52.00, 2006, 1107);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Real Time Worlds', 'Action-Adventure', 'Mature', 1107);
insert into Product(title, amount_in_stock, price, year, id) values ('Dead or Alive 4', 6, 46.00, 2004, 1108);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Team Ninja', 'Fighting', 'Mature', 1108);
insert into Product(title, amount_in_stock, price, year, id) values ('Dead Rising', 1, 39.00, 2005, 1109);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Capcom', 'Horror', 'Mature', 1109);
insert into Product(title, amount_in_stock, price, year, id) values ('Fable II', 4, 33.00, 2005, 1110);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Lionhead Studios', 'Action Role-Playing', 'Mature', 1110);
insert into Product(title, amount_in_stock, price, year, id) values ('Fallout 3', 4, 59.00, 2000, 1111);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Bethesda Softworks', 'Action Role-Playing', 'Mature', 1111);
insert into Product(title, amount_in_stock, price, year, id) values ('Fight Night Round 3', 3, 33.00, 2006, 1112);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'EA Chicago', 'Sports', 'Teen', 1112);
insert into Product(title, amount_in_stock, price, year, id) values ('Forza Motorsport 2', 5, 51.00, 2006, 1113);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Turn 10 Studios', 'Racing', 'Everyone', 1113);
insert into Product(title, amount_in_stock, price, year, id) values ('Gears of War', 3, 68.00, 2008, 1114);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Epic Games', 'Third-Person Shooter', 'Mature', 1114);
insert into Product(title, amount_in_stock, price, year, id) values ('Gears of War 2', 3, 69.00, 2005, 1115);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Epic Games', 'Third-Person Shooter', 'Mature', 1115);
insert into Product(title, amount_in_stock, price, year, id) values ('Grand Theft Auto IV', 1, 49.00, 2001, 1116);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Rockstar North', 'Third-Person Shooter', 'Mature', 1116);
insert into Product(title, amount_in_stock, price, year, id) values ('Guitar Hero II', 2, 35.00, 2002, 1117);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Harmonix Music Systems', 'Music', 'Teen', 1117);
insert into Product(title, amount_in_stock, price, year, id) values ('Guitar Hero III: Legends of Rock', 1, 48.00, 2004, 1118);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Neversoft', 'Music', 'Teen', 1118);
insert into Product(title, amount_in_stock, price, year, id) values ('Halo 3', 2, 60.00, 2000, 1119);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Bungie', 'First-Person Shooter', 'Mature', 1119);
insert into Product(title, amount_in_stock, price, year, id) values ('Halo Wars', 6, 38.00, 2005, 1120);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Ensemble Studios', 'Real-Time Strategy', 'Teen', 1120);
insert into Product(title, amount_in_stock, price, year, id) values ('Left 4 Dead', 2, 34.00, 2000, 1121);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Certain Affinity', 'Horror', 'Mature', 1121);
insert into Product(title, amount_in_stock, price, year, id) values ('Lost Planet: Extreme Condition', 5, 68.00, 2009, 1122);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Capcom', 'Third-Person Shooter', 'Teen', 1122);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 07', 2, 42.00, 2000, 1123);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'EA Tiburon', 'Sports', 'Everyone', 1123);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 08', 6, 70.00, 2008, 1124);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'EA Tiburon', 'Sports', 'Everyone', 1124);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 09', 2, 68.00, 2006, 1125);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'EA Tiburon', 'Sports', 'Everyone', 1125);
insert into Product(title, amount_in_stock, price, year, id) values ('Marvel: Ultimate Alliance', 2, 68.00, 2005, 1126);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Raven Software', 'Action Role-Playing', 'Teen', 1126);
insert into Product(title, amount_in_stock, price, year, id) values ('Mass Effect', 3, 45.00, 2007, 1127);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'BioWare', 'Action Role-Playing', 'Mature', 1127);
insert into Product(title, amount_in_stock, price, year, id) values ('Ninja Gaiden II', 4, 68.00, 2003, 1128);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Team Ninja', 'Action-Adventure', 'Mature', 1128);
insert into Product(title, amount_in_stock, price, year, id) values ('Perfect Dark Zero', 5, 40.00, 2003, 1129);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Rare Ltd.', 'First-Person Shooter', 'Mature', 1129);
insert into Product(title, amount_in_stock, price, year, id) values ('Saints Row', 3, 44.00, 2006, 1130);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Volition Inc.', 'Action-Adventure', 'Mature', 1130);
insert into Product(title, amount_in_stock, price, year, id) values ('The Elder Scrolls IV: Oblivion', 4, 57.00, 2005, 1131);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Bethesda Softworks', 'Action Role-Playing', 'Teen', 1131);
insert into Product(title, amount_in_stock, price, year, id) values ('The Orange Box', 1, 70.00, 2003, 1132);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Valve Corporation', 'First-Person Shooter', 'Mature', 1132);
insert into Product(title, amount_in_stock, price, year, id) values ('Tom Clancys Ghost Recon Advanced Warfighter', 4, 38.00, 2001, 1133);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Red Storm Entertainment', 'Tactical Shooter', 'Teen', 1133);
insert into Product(title, amount_in_stock, price, year, id) values ('Tom Clancys Ghost Recon Advanced Warfighter 2', 1, 39.00, 2009, 1134);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Red Storm Entertainment', 'Tactical Shooter', 'Teen', 1134);
insert into Product(title, amount_in_stock, price, year, id) values ('Tom Clancys Rainbow Six: Vegas', 3, 42.00, 2004, 1135);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Ubisoft Montreal', 'Tactical Shooter', 'Mature', 1135);
insert into Product(title, amount_in_stock, price, year, id) values ('Uno', 6, 58.00, 2005, 1136);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Carbonated Games', 'Card and Board', 'Everyone', 1136);
insert into Product(title, amount_in_stock, price, year, id) values ('Viva Piñata', 4, 39.00, 2006, 1137);
insert into Game(platform, developer, genre, rating, pid) values ('Xbox 360', 'Rare Ltd.', 'Life Simulation', 'Everyone', 1137);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty 3', 6, 58.00, 2006, 1138);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Treyarch', 'First-Person Shooter', 'Teen', 1138);
insert into Product(title, amount_in_stock, price, year, id) values ('Gran Turismo 5 Prologue', 1, 58.00, 2003, 1139);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Polyphony Digital', 'Racing', 'Everyone', 1139);
insert into Product(title, amount_in_stock, price, year, id) values ('Grand Theft Auto IV', 6, 30.00, 2005, 1140);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Rockstar North', 'Sandbox', 'Mature', 1140);
insert into Product(title, amount_in_stock, price, year, id) values ('Heavenly Sword', 6, 56.00, 2005, 1141);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Ninja Theory', 'Action-Adventure', 'Teen', 1141);
insert into Product(title, amount_in_stock, price, year, id) values ('Killzone 2', 5, 55.00, 2005, 1142);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Guerilla Games', 'First-Person Shooter', 'Mature', 1142);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 07', 4, 63.00, 2005, 1143);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'EA Tiburon', 'Sports', 'Everyone', 1143);
insert into Product(title, amount_in_stock, price, year, id) values ('Marvel: Ultimate Alliance', 3, 66.00, 2003, 1144);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Raven Software', 'Action Role-Playing', 'Teen', 1144);
insert into Product(title, amount_in_stock, price, year, id) values ('Metal Gear Solid 4: Guns of the Patriots', 2, 69.00, 2000, 1145);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Kojima Productions', 'Stealth Action', 'Mature', 1145);
insert into Product(title, amount_in_stock, price, year, id) values ('MotorStorm', 5, 69.00, 2007, 1146);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Evolution Studios', 'Racing', 'Teen', 1146);
insert into Product(title, amount_in_stock, price, year, id) values ('MotorStorm: Pacific Rift', 6, 46.00, 2007, 1147);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Evolution Studios', 'Racing', 'Teen', 1147);
insert into Product(title, amount_in_stock, price, year, id) values ('NBA 07', 3, 38.00, 2005, 1148);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'SCE Studios San Diego', 'Sports', 'Everyone', 1148);
insert into Product(title, amount_in_stock, price, year, id) values ('NBA 2K7', 5, 60.00, 2005, 1149);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Visual Concepts', 'Sports', 'Everyone', 1149);
insert into Product(title, amount_in_stock, price, year, id) values ('Need for Speed: Carbon', 2, 66.00, 2003, 1150);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'EA Black Box', 'Racing', 'Everyone', 1150);
insert into Product(title, amount_in_stock, price, year, id) values ('Ratchet & Clank Future: Tools of Destruction', 5, 51.00, 2006, 1151);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Insomniac Games', 'Platform', 'Everyone', 1151);
insert into Product(title, amount_in_stock, price, year, id) values ('Resistance: Fall of Man', 4, 61.00, 2002, 1152);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Insomniac Games', 'First-Person Shooter', 'Mature', 1152);
insert into Product(title, amount_in_stock, price, year, id) values ('Ridge Racer 7', 3, 48.00, 2001, 1153);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Namco Bandai', 'Racing', 'Everyone', 1153);
insert into Product(title, amount_in_stock, price, year, id) values ('Tony Hawks Project 8', 5, 40.00, 2007, 1154);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Neversoft', 'Sports', 'Teen', 1154);
insert into Product(title, amount_in_stock, price, year, id) values ('Uncharted: Drakes Fortune', 4, 31.00, 2005, 1155);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Naughty Dog', 'Action-Adventure', 'Teen', 1155);
insert into Product(title, amount_in_stock, price, year, id) values ('Untold Legends: Dark Kingdom', 2, 59.00, 2003, 1156);
insert into Game(platform, developer, genre, rating, pid) values ('Playstation 3', 'Sony Online Entertainment', 'Hack-and-Slash', 'Teen', 1156);
insert into Product(title, amount_in_stock, price, year, id) values ('BlastWorks: Build Trade Destroy', 6, 58.00, 2006, 1157);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Budcat Creations', 'Scrolling Shooter', 'Everyone', 1157);
insert into Product(title, amount_in_stock, price, year, id) values ('Boom Blox', 2, 43.00, 2008, 1158);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Los Angeles', 'Puzzle', 'Everyone', 1158);
insert into Product(title, amount_in_stock, price, year, id) values ('Boom Blox Bash Party', 1, 69.00, 2008, 1159);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Los Angeles', 'Puzzle', 'Everyone', 1159);
insert into Product(title, amount_in_stock, price, year, id) values ('Bully: Scholarship Edition', 6, 47.00, 2007, 1160);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Rockstar Toronto', 'Action-Adventure', 'Teen', 1160);
insert into Product(title, amount_in_stock, price, year, id) values ('Call of Duty: World at War', 4, 38.00, 2003, 1161);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Treyarch', 'First-Person Shooter', 'Mature', 1161);
insert into Product(title, amount_in_stock, price, year, id) values ('de Blob', 1, 48.00, 2002, 1162);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Blue Tongue Entertainment', 'Platform', 'Everyone', 1162);
insert into Product(title, amount_in_stock, price, year, id) values ('Donkey Kong Jungle Beat', 3, 63.00, 2004, 1163);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Nintendo EAD Tokyo', 'Platform', 'Everyone', 1163);
insert into Product(title, amount_in_stock, price, year, id) values ('EA Sports Active', 3, 70.00, 2000, 1164);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Sports', 'Fitness', 'Everyone', 1164);
insert into Product(title, amount_in_stock, price, year, id) values ('Excitebots: Trick Racing', 3, 55.00, 2005, 1165);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Monster Games', 'Racing', 'Everyone', 1165);
insert into Product(title, amount_in_stock, price, year, id) values ('Guitar Hero III: Legends of Rock', 4, 59.00, 2003, 1166);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Vicarious Visions', '"Music, Rhythm"', 'Teen', 1166);
insert into Product(title, amount_in_stock, price, year, id) values ('Guitar Hero: Metallica', 1, 66.00, 2002, 1167);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Budcat Creations', '"Music, Rhythm"', 'Teen', 1167);
insert into Product(title, amount_in_stock, price, year, id) values ('Guitar Hero: World Tour', 4, 56.00, 2000, 1168);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Vicarious Visions', '"Music, Rhythm"', 'Teen', 1168);
insert into Product(title, amount_in_stock, price, year, id) values ('Little Kings Story', 5, 48.00, 2008, 1169);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Cing', 'Role-Playing', 'Everyone', 1169);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 07', 3, 44.00, 2009, 1170);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Tiburon', 'Sports', 'Everyone', 1170);
insert into Product(title, amount_in_stock, price, year, id) values ('Madden NFL 09 All-Play', 5, 49.00, 2006, 1171);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Tiburon', 'Sports', 'Everyone', 1171);
insert into Product(title, amount_in_stock, price, year, id) values ('MadWorld', 6, 37.00, 2001, 1172);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Platinum Games', 'Beam em Up', 'Mature', 1172);
insert into Product(title, amount_in_stock, price, year, id) values ('Mario Kart Wii', 3, 60.00, 2002, 1173);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Nintendo EAD', 'Racing', 'Everyone', 1173);
insert into Product(title, amount_in_stock, price, year, id) values ('Metroid Prime 3: Corruption', 5, 40.00, 2007, 1174);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Retro Studios', 'First-Person Action-Adventure', 'Teen', 1174);
insert into Product(title, amount_in_stock, price, year, id) values ('MLB Power Pros', 3, 49.00, 2003, 1175);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Konami', 'Sports', 'Everyone', 1175);
insert into Product(title, amount_in_stock, price, year, id) values ('No More Heroes', 3, 69.00, 2004, 1176);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Grasshopper Manufacture', 'Action-Adventure', 'Mature', 1176);
insert into Product(title, amount_in_stock, price, year, id) values ('Okami', 3, 46.00, 2008, 1177);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Ready at Dawn', 'Action-Adventure', 'Teen', 1177);
insert into Product(title, amount_in_stock, price, year, id) values ('Pikmin 2', 3, 65.00, 2008, 1178);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Nintendo EAD', 'Real-Time Strategy', 'Everyone', 1178);
insert into Product(title, amount_in_stock, price, year, id) values ('Pinball Hall of Fame: The Williams Collection', 3, 58.00, 2001, 1179);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'FarSight Studios', 'Pinball', 'Everyone', 1179);
insert into Product(title, amount_in_stock, price, year, id) values ('Pro Evolution Soccer 2008', 6, 51.00, 2003, 1180);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Konami', 'Sports', 'Everyone', 1180);
insert into Product(title, amount_in_stock, price, year, id) values ('Pro Evolution Soccer 2009', 2, 45.00, 2001, 1181);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Konami', 'Sports', 'Everyone', 1181);
insert into Product(title, amount_in_stock, price, year, id) values ('Punch-Out!!', 1, 47.00, 2007, 1182);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Next Level Games', 'Sports', 'Everyone', 1182);
insert into Product(title, amount_in_stock, price, year, id) values ('Resident Evil 4: Wii Edition', 3, 32.00, 2003, 1183);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Capcom', 'Horror', 'Mature', 1183);
insert into Product(title, amount_in_stock, price, year, id) values ('Rock Band', 6, 59.00, 2009, 1184);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Pi Studios', 'Music', 'Teen', 1184);
insert into Product(title, amount_in_stock, price, year, id) values ('Rock Band 2', 5, 63.00, 2007, 1185);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Pi Studios', 'Music', 'Teen', 1185);
insert into Product(title, amount_in_stock, price, year, id) values ('Super Mario Galaxy', 6, 31.00, 2008, 1186);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Nintendo EAD Tokyo', 'Platform', 'Everyone', 1186);
insert into Product(title, amount_in_stock, price, year, id) values ('Super Paper Mario', 1, 69.00, 2005, 1187);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Intelligent Systems', 'Platform', 'Everyone', 1187);
insert into Product(title, amount_in_stock, price, year, id) values ('Super Smash Bros. Brawl', 1, 31.00, 2004, 1188);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Sora', 'Fighting', 'Teen', 1188);
insert into Product(title, amount_in_stock, price, year, id) values ('The House of the Dead: Overkill', 3, 51.00, 2002, 1189);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Headstrong Games', 'Rail Shooter', 'Mature', 1189);
insert into Product(title, amount_in_stock, price, year, id) values ('The Legend of Zelda: Twilight Princess', 5, 33.00, 2001, 1190);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Nintendo EAD', 'Action-Adventure', 'Teen', 1190);
insert into Product(title, amount_in_stock, price, year, id) values ('Tiger Woods PGA Tour 09 All-Play', 5, 40.00, 2009, 1191);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'EA Tiburon', 'Sports', 'Everyone', 1191);
insert into Product(title, amount_in_stock, price, year, id) values ('WarioWare: Smooth Moves', 3, 70.00, 2002, 1192);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Intelligent Systems', 'Party', 'Everyone', 1192);
insert into Product(title, amount_in_stock, price, year, id) values ('WWE SmackDown vs. RAW 2009', 4, 35.00, 2008, 1193);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Yukes', 'Fighting', 'Teen', 1193);
insert into Product(title, amount_in_stock, price, year, id) values ('Zack & Wiki: Quest for Barbaros Treasure', 2, 41.00, 2001, 1194);
insert into Game(platform, developer, genre, rating, pid) values ('Wii', 'Capcom', 'Adventure', 'Everyone', 1194);
