--insert into Product(title, amount_in_stock, price, year, id) values ('Title', Quantity, Price, Year, 1300);
--insert into Movie(director, rating, genre, pid) values ('Director', 'Rating', 'Genre', 1300);
insert into Product(title, amount_in_stock, price, year, id) values ('Ghost', 1, 24.00, 1990, 1301);
insert into Movie(director, rating, genre, pid) values ('Jerry Zucker', 'PG-13', 'Drama', 1301);
insert into Product(title, amount_in_stock, price, year, id) values ('Home Alone', 2, 25.00, 1990, 1302);
insert into Movie(director, rating, genre, pid) values ('Chris Columbus', 'PG-13', 'Comedy', 1302);
insert into Product(title, amount_in_stock, price, year, id) values ('Pretty Woman', 3, 15.00, 1990, 1303);
insert into Movie(director, rating, genre, pid) values ('Garry Marshall', 'PG-13', 'Romantic Comedy', 1303);
insert into Product(title, amount_in_stock, price, year, id) values ('Dances With Wolves', 2, 15.00, 1990, 1304);
insert into Movie(director, rating, genre, pid) values ('Kevin Costner', 'PG-13', 'Drama', 1304);
insert into Product(title, amount_in_stock, price, year, id) values ('Total Recall', 5, 19.00, 1990, 1305);
insert into Movie(director, rating, genre, pid) values ('Paul Verhoeven', 'R', 'Action', 1305);
insert into Product(title, amount_in_stock, price, year, id) values ('Back to the Future III', 2, 23.00, 1990, 1306);
insert into Movie(director, rating, genre, pid) values ('Robert Zemeckis', 'PG-13', 'Comedy', 1306);
insert into Product(title, amount_in_stock, price, year, id) values ('Die Hard 2 : Die Harder', 6, 18.00, 1990, 1307);
insert into Movie(director, rating, genre, pid) values ('Renny Harlin', 'R', 'Action', 1307);
insert into Product(title, amount_in_stock, price, year, id) values ('Presumed Innocent', 3, 22.00, 1990, 1308);
insert into Movie(director, rating, genre, pid) values ('Alan J. Pakula', 'R', 'Drama', 1308);
insert into Product(title, amount_in_stock, price, year, id) values ('Teenage Mutant Ninja Turtles', 3, 15.00, 1990, 1309);
insert into Movie(director, rating, genre, pid) values ('Steve Barron', 'PG', 'Action', 1309);
insert into Product(title, amount_in_stock, price, year, id) values ('Kindergarten Cop', 3, 19.00, 1990, 1310);
insert into Movie(director, rating, genre, pid) values ('Ivan Reitman', 'PG', 'Comedy', 1310);
insert into Product(title, amount_in_stock, price, year, id) values ('Terminator 2 : Judgment Day', 6, 24.00, 1991, 1311);
insert into Movie(director, rating, genre, pid) values ('James Cameron', 'R', 'Action', 1311);
insert into Product(title, amount_in_stock, price, year, id) values ('Robin Hood: Prince of Thieves', 2, 20.00, 1991, 1312);
insert into Movie(director, rating, genre, pid) values ('Kevin Reynolds', 'PG-13', 'Action', 1312);
insert into Product(title, amount_in_stock, price, year, id) values ('Beauty and the Beast', 2, 21.00, 1991, 1313);
insert into Movie(director, rating, genre, pid) values ('Gary Trousdale', 'G', 'Animation', 1313);
insert into Product(title, amount_in_stock, price, year, id) values ('The Silence of the Lambs', 5, 20.00, 1991, 1314);
insert into Movie(director, rating, genre, pid) values ('Jonathan Demme', 'R', 'Horror/Suspense', 1314);
insert into Product(title, amount_in_stock, price, year, id) values ('City Slickers', 2, 17.00, 1991, 1315);
insert into Movie(director, rating, genre, pid) values ('Ron Underwood', 'R', 'Comedy', 1315);
insert into Product(title, amount_in_stock, price, year, id) values ('Hook', 1, 15.00, 1991, 1316);
insert into Movie(director, rating, genre, pid) values ('Steven Speilberg', 'PG', 'Adventure', 1316);
insert into Product(title, amount_in_stock, price, year, id) values ('The Addams Family', 1, 16.00, 1991, 1317);
insert into Movie(director, rating, genre, pid) values ('Barry Sonnenfeld', 'PG-13', 'Comedy', 1317);
insert into Product(title, amount_in_stock, price, year, id) values ('Sleeping with the Enemy', 1, 23.00, 1991, 1318);
insert into Movie(director, rating, genre, pid) values ('Joseph Ruben', 'R', 'Drama', 1318);
insert into Product(title, amount_in_stock, price, year, id) values ('Father of the Bride', 4, 21.00, 1991, 1319);
insert into Movie(director, rating, genre, pid) values ('Charles Shyer', 'PG-13', 'Comedy', 1319);
insert into Product(title, amount_in_stock, price, year, id) values ('The Naked Gun 2 1/2: The Smell of Fear', 1, 17.00, 1991, 1320);
insert into Movie(director, rating, genre, pid) values ('David Zucker', 'R', 'Comedy', 1320);
insert into Product(title, amount_in_stock, price, year, id) values ('Aladdin', 2, 18.00, 1992, 1321);
insert into Movie(director, rating, genre, pid) values ('Ron Clements', 'G', 'Animation', 1321);
insert into Product(title, amount_in_stock, price, year, id) values ('Home Alone 2: Lost in New York', 2, 16.00, 1992, 1322);
insert into Movie(director, rating, genre, pid) values ('Chris Columbus', 'PG-13', 'Comedy', 1322);
insert into Product(title, amount_in_stock, price, year, id) values ('Batman Returns', 6, 19.00, 1992, 1323);
insert into Movie(director, rating, genre, pid) values ('Tim Burton', 'PG-13', 'Adventure', 1323);
insert into Product(title, amount_in_stock, price, year, id) values ('Lethal Weapon 3', 1, 23.00, 1992, 1324);
insert into Movie(director, rating, genre, pid) values ('Richard Donner', 'R', 'Action', 1324);
insert into Product(title, amount_in_stock, price, year, id) values ('A Few Good Men', 6, 23.00, 1992, 1325);
insert into Movie(director, rating, genre, pid) values ('Aaron Sorkin', 'R', 'Drama', 1325);
insert into Product(title, amount_in_stock, price, year, id) values ('Sister Act', 6, 24.00, 1992, 1326);
insert into Movie(director, rating, genre, pid) values ('Emile Ardolino', 'PG-13', 'Comedy', 1326);
insert into Product(title, amount_in_stock, price, year, id) values ('The Bodyguard', 3, 22.00, 1992, 1327);
insert into Movie(director, rating, genre, pid) values ('Mick Jackson', 'R', 'Action', 1327);
insert into Product(title, amount_in_stock, price, year, id) values ('Waynes World', 2, 17.00, 1992, 1328);
insert into Movie(director, rating, genre, pid) values ('Penelope Spheeris', 'PG-13', 'Comedy', 1328);
insert into Product(title, amount_in_stock, price, year, id) values ('Basic Instinct', 2, 17.00, 1992, 1329);
insert into Movie(director, rating, genre, pid) values ('Paul Verhoeven', 'R', 'Horror/Suspense', 1329);
insert into Product(title, amount_in_stock, price, year, id) values ('A League of Their Own', 4, 21.00, 1992, 1330);
insert into Movie(director, rating, genre, pid) values ('Penny Marshall', 'PG-13', 'Comedy', 1330);
insert into Product(title, amount_in_stock, price, year, id) values ('Jurassic Park', 1, 18.00, 1993, 1331);
insert into Movie(director, rating, genre, pid) values ('Steven Speilberg', 'PG-13', 'Adventure', 1331);
insert into Product(title, amount_in_stock, price, year, id) values ('Mrs. Doubtfire', 4, 17.00, 1993, 1332);
insert into Movie(director, rating, genre, pid) values ('Chris Columbus', 'PG-13', 'Comedy', 1332);
insert into Product(title, amount_in_stock, price, year, id) values ('The Fugitive', 4, 18.00, 1993, 1333);
insert into Movie(director, rating, genre, pid) values ('Andrew Davis', 'R', 'Action', 1333);
insert into Product(title, amount_in_stock, price, year, id) values ('The Firm', 4, 21.00, 1993, 1334);
insert into Movie(director, rating, genre, pid) values ('Sydney Pollack', 'R', 'Drama', 1334);
insert into Product(title, amount_in_stock, price, year, id) values ('Sleepless in Seattle', 5, 20.00, 1993, 1335);
insert into Movie(director, rating, genre, pid) values ('Nora Ephron', 'PG-13', 'Romantic Comedy', 1335);
insert into Product(title, amount_in_stock, price, year, id) values ('Indecent Proposal', 6, 24.00, 1993, 1336);
insert into Movie(director, rating, genre, pid) values ('Adrian Lyne', 'R', 'Drama', 1336);
insert into Product(title, amount_in_stock, price, year, id) values ('In the Line of Fire', 3, 22.00, 1993, 1337);
insert into Movie(director, rating, genre, pid) values ('Wolfgang Petersen', 'R', 'Thriller', 1337);
insert into Product(title, amount_in_stock, price, year, id) values ('The Pelican Brief', 3, 25.00, 1993, 1338);
insert into Movie(director, rating, genre, pid) values ('Alan J. Pakula', 'R', 'Thriller', 1338);
insert into Product(title, amount_in_stock, price, year, id) values ('Schindlers List', 5, 17.00, 1993, 1339);
insert into Movie(director, rating, genre, pid) values ('Steven Speilberg', 'R', 'Drama', 1339);
insert into Product(title, amount_in_stock, price, year, id) values ('Cliffhanger', 3, 17.00, 1993, 1340);
insert into Movie(director, rating, genre, pid) values ('Renny Harlin', 'R', 'Action', 1340);
insert into Product(title, amount_in_stock, price, year, id) values ('Forrest Gump', 3, 23.00, 1994, 1341);
insert into Movie(director, rating, genre, pid) values ('Robert Zemeckis', 'PG-13', 'Drama', 1341);
insert into Product(title, amount_in_stock, price, year, id) values ('The Lion King*', 6, 21.00, 1994, 1342);
insert into Movie(director, rating, genre, pid) values ('Roger Allers', 'G', 'Animation', 1342);
insert into Product(title, amount_in_stock, price, year, id) values ('True Lies', 2, 16.00, 1994, 1343);
insert into Movie(director, rating, genre, pid) values ('James Cameron', 'R', 'Action', 1343);
insert into Product(title, amount_in_stock, price, year, id) values ('The Santa Clause', 6, 16.00, 1994, 1344);
insert into Movie(director, rating, genre, pid) values ('John Pasquin', 'PG', 'Comedy', 1344);
insert into Product(title, amount_in_stock, price, year, id) values ('The Flintstones', 5, 21.00, 1994, 1345);
insert into Movie(director, rating, genre, pid) values ('Brian Levant', 'PG', 'Comedy', 1345);
insert into Product(title, amount_in_stock, price, year, id) values ('Dumb and Dumber', 2, 17.00, 1994, 1346);
insert into Movie(director, rating, genre, pid) values ('Peter Farrelly', 'PG-13', 'Comedy', 1346);
insert into Product(title, amount_in_stock, price, year, id) values ('Clear and Present Danger', 2, 16.00, 1994, 1347);
insert into Movie(director, rating, genre, pid) values ('Phillip Noyce', 'R', 'Thriller', 1347);
insert into Product(title, amount_in_stock, price, year, id) values ('Speed', 3, 15.00, 1994, 1348);
insert into Movie(director, rating, genre, pid) values ('Jan de Bont', 'R', 'Action', 1348);
insert into Product(title, amount_in_stock, price, year, id) values ('The Mask', 5, 19.00, 1994, 1349);
insert into Movie(director, rating, genre, pid) values ('Chuck Russell', 'PG-13', 'Comedy', 1349);
insert into Product(title, amount_in_stock, price, year, id) values ('Pulp Fiction', 3, 21.00, 1994, 1350);
insert into Movie(director, rating, genre, pid) values ('Quentin Tarantino', 'R', 'Crime', 1350);
insert into Product(title, amount_in_stock, price, year, id) values ('Toy Story', 3, 18.00, 1995, 1351);
insert into Movie(director, rating, genre, pid) values ('John Lasseter', 'G', 'Animation', 1351);
insert into Product(title, amount_in_stock, price, year, id) values ('Batman Forever', 3, 17.00, 1995, 1352);
insert into Movie(director, rating, genre, pid) values ('Joel Schumacher', 'PG-13', 'Action', 1352);
insert into Product(title, amount_in_stock, price, year, id) values ('Apollo 13', 6, 16.00, 1995, 1353);
insert into Movie(director, rating, genre, pid) values ('Ron Howard', 'PG-13', 'Drama', 1353);
insert into Product(title, amount_in_stock, price, year, id) values ('Pocahontas', 2, 22.00, 1995, 1354);
insert into Movie(director, rating, genre, pid) values ('Mike Gabriel', 'G', 'Animation', 1354);
insert into Product(title, amount_in_stock, price, year, id) values ('Ace Ventura : When Nature Calls', 4, 21.00, 1995, 1355);
insert into Movie(director, rating, genre, pid) values ('Steve Oedekerk', 'PG-13', 'Comedy', 1355);
insert into Product(title, amount_in_stock, price, year, id) values ('GoldenEye', 5, 25.00, 1995, 1356);
insert into Movie(director, rating, genre, pid) values ('Martin Campbell', 'PG-13', 'Action', 1356);
insert into Product(title, amount_in_stock, price, year, id) values ('Jumanji', 4, 20.00, 1995, 1357);
insert into Movie(director, rating, genre, pid) values ('Joe Johnston', 'PG', 'Adventure', 1357);
insert into Product(title, amount_in_stock, price, year, id) values ('Casper', 4, 22.00, 1995, 1358);
insert into Movie(director, rating, genre, pid) values ('Brad Silberling', 'PG', 'Adventure', 1358);
insert into Product(title, amount_in_stock, price, year, id) values ('Se7en', 4, 23.00, 1995, 1359);
insert into Movie(director, rating, genre, pid) values ('David Fincher', 'R', 'Crime', 1359);
insert into Product(title, amount_in_stock, price, year, id) values ('Die Hard With A Vengeance*', 1, 20.00, 1995, 1360);
insert into Movie(director, rating, genre, pid) values ('John McTiernan', 'R', 'Action', 1360);
insert into Product(title, amount_in_stock, price, year, id) values ('Independence Day', 4, 16.00, 1996, 1361);
insert into Movie(director, rating, genre, pid) values ('Roland Emmerich', 'PG-13', 'Science Fiction', 1361);
insert into Product(title, amount_in_stock, price, year, id) values ('Twister', 4, 25.00, 1996, 1362);
insert into Movie(director, rating, genre, pid) values ('Jan de Bront', 'PG-13', 'Drama', 1362);
insert into Product(title, amount_in_stock, price, year, id) values ('Mission: Impossible', 3, 25.00, 1996, 1363);
insert into Movie(director, rating, genre, pid) values ('Brian De Palma', 'PG-13', 'Action', 1363);
insert into Product(title, amount_in_stock, price, year, id) values ('Jerry Maguire', 2, 20.00, 1996, 1364);
insert into Movie(director, rating, genre, pid) values ('Cameron Crowe', 'PG-13', 'Comedy', 1364);
insert into Product(title, amount_in_stock, price, year, id) values ('Ransom', 2, 19.00, 1996, 1365);
insert into Movie(director, rating, genre, pid) values ('Ron Howard', 'R', 'Thriller', 1365);
insert into Product(title, amount_in_stock, price, year, id) values ('101 Dalmatians', 4, 19.00, 1996, 1366);
insert into Movie(director, rating, genre, pid) values ('Stephen Herek', 'R', 'Adventure', 1366);
insert into Product(title, amount_in_stock, price, year, id) values ('The Rock', 1, 15.00, 1996, 1367);
insert into Movie(director, rating, genre, pid) values ('Tom Shadyac', 'PG-13', 'Comedy', 1367);
insert into Product(title, amount_in_stock, price, year, id) values ('The Nutty Professor', 5, 21.00, 1996, 1368);
insert into Movie(director, rating, genre, pid) values ('Mike Nichols', 'PG-13', 'Comedy', 1368);
insert into Product(title, amount_in_stock, price, year, id) values ('The Birdcage', 2, 20.00, 1996, 1369);
insert into Movie(director, rating, genre, pid) values ('Joel Schumacher', 'R', 'Thriller', 1369);
insert into Product(title, amount_in_stock, price, year, id) values ('A Time to Kill', 1, 19.00, 1996, 1370);
insert into Movie(director, rating, genre, pid) values ('J Masterson', 'R', 'Drama', 1370);
insert into Product(title, amount_in_stock, price, year, id) values ('Titanic', 3, 21.00, 1997, 1371);
insert into Movie(director, rating, genre, pid) values ('Joel Schumacher', 'PG-13', 'Drama', 1371);
insert into Product(title, amount_in_stock, price, year, id) values ('The Lost World: Jurassic Park', 5, 18.00, 1997, 1372);
insert into Movie(director, rating, genre, pid) values ('Steven Spielberg', 'PG-13', 'Action', 1372);
insert into Product(title, amount_in_stock, price, year, id) values ('Men in Black', 5, 17.00, 1997, 1373);
insert into Movie(director, rating, genre, pid) values ('Barry Sonnerfeld', 'PG-13', 'Science Fiction', 1373);
insert into Product(title, amount_in_stock, price, year, id) values ('Tomorrow Never Dies', 1, 21.00, 1997, 1374);
insert into Movie(director, rating, genre, pid) values ('Roger Spottiswoode', 'PG-13', 'Action', 1374);
insert into Product(title, amount_in_stock, price, year, id) values ('Air Force One', 2, 16.00, 1997, 1375);
insert into Movie(director, rating, genre, pid) values ('Wolfgang Petersen', 'R', 'Action', 1375);
insert into Product(title, amount_in_stock, price, year, id) values ('As Good as It Gets', 4, 22.00, 1997, 1376);
insert into Movie(director, rating, genre, pid) values ('James L. Brooks', 'R', 'Comedy', 1376);
insert into Product(title, amount_in_stock, price, year, id) values ('Liar Liar', 5, 24.00, 1997, 1377);
insert into Movie(director, rating, genre, pid) values ('Tom Shadyac', 'PG-13', 'Comedy', 1377);
insert into Product(title, amount_in_stock, price, year, id) values ('My Best Friends Wedding', 1, 22.00, 1997, 1378);
insert into Movie(director, rating, genre, pid) values ('P. J. Hogan', 'PG-13', 'Romantic Comedy', 1378);
insert into Product(title, amount_in_stock, price, year, id) values ('The Fifth Element', 5, 25.00, 1997, 1379);
insert into Movie(director, rating, genre, pid) values ('Luc Besson', 'PG-13', 'Science Fiction', 1379);
insert into Product(title, amount_in_stock, price, year, id) values ('The Full Monty', 3, 24.00, 1997, 1380);
insert into Movie(director, rating, genre, pid) values ('Peter Cattaneo', 'R', 'Comedy', 1380);
insert into Product(title, amount_in_stock, price, year, id) values ('Armageddon', 4, 24.00, 1998, 1381);
insert into Movie(director, rating, genre, pid) values ('Michael Bay', 'PG-13', 'Horror/Suspense', 1381);
insert into Product(title, amount_in_stock, price, year, id) values ('Saving Private Ryan', 5, 25.00, 1998, 1382);
insert into Movie(director, rating, genre, pid) values ('Steven Speilberg', 'R', 'War', 1382);
insert into Product(title, amount_in_stock, price, year, id) values ('Godzilla', 4, 22.00, 1998, 1383);
insert into Movie(director, rating, genre, pid) values ('Roland Emmerich', 'PG-13', 'Science Fiction', 1383);
insert into Product(title, amount_in_stock, price, year, id) values ('Theres Something About Mary', 2, 24.00, 1998, 1384);
insert into Movie(director, rating, genre, pid) values ('Bobby Farrelly', 'PG-13', 'Science Fiction', 1384);
insert into Product(title, amount_in_stock, price, year, id) values ('A Bugs Life', 2, 18.00, 1998, 1385);
insert into Movie(director, rating, genre, pid) values ('John Lasseter', 'PG', 'Animation', 1385);
insert into Product(title, amount_in_stock, price, year, id) values ('Deep Impact', 6, 17.00, 1998, 1386);
insert into Movie(director, rating, genre, pid) values ('Mimi Leder', 'R', 'Science Fiction', 1386);
insert into Product(title, amount_in_stock, price, year, id) values ('Mulan', 6, 19.00, 1998, 1387);
insert into Movie(director, rating, genre, pid) values ('Tony Bancroft', 'G', 'Animation', 1387);
insert into Product(title, amount_in_stock, price, year, id) values ('Dr. Dolittle', 6, 23.00, 1998, 1388);
insert into Movie(director, rating, genre, pid) values ('Betty Thomas', 'PG-13', 'Comedy', 1388);
insert into Product(title, amount_in_stock, price, year, id) values ('Shakespeare in Love', 5, 18.00, 1998, 1389);
insert into Movie(director, rating, genre, pid) values ('John Madden', 'PG-13', 'Romantic Comedy', 1389);
insert into Product(title, amount_in_stock, price, year, id) values ('Lethal Weapon 4', 3, 19.00, 1998, 1390);
insert into Movie(director, rating, genre, pid) values ('Richard Donner', 'R', 'Action', 1390);
insert into Product(title, amount_in_stock, price, year, id) values ('Star Wars Episode I: The Phantom Menace', 5, 15.00, 1999, 1391);
insert into Movie(director, rating, genre, pid) values ('George Lucas', 'PG-13', 'Science Fiction', 1391);
insert into Product(title, amount_in_stock, price, year, id) values ('The Sixth Sense', 3, 18.00, 1999, 1392);
insert into Movie(director, rating, genre, pid) values ('M. Night Shyamalan', 'PG-13', 'Thriller', 1392);
insert into Product(title, amount_in_stock, price, year, id) values ('Toy Story 2', 2, 20.00, 1999, 1393);
insert into Movie(director, rating, genre, pid) values ('John Lasseter', 'PG', 'Animation', 1393);
insert into Product(title, amount_in_stock, price, year, id) values ('The Matrix', 1, 20.00, 1999, 1394);
insert into Movie(director, rating, genre, pid) values ('Wachowski Brothers', 'R', 'Science Fiction', 1394);
insert into Product(title, amount_in_stock, price, year, id) values ('Tarzan', 2, 16.00, 1999, 1395);
insert into Movie(director, rating, genre, pid) values ('Chris Buck', 'PG', 'Animation', 1395);
insert into Product(title, amount_in_stock, price, year, id) values ('The Mummy', 2, 16.00, 1999, 1396);
insert into Movie(director, rating, genre, pid) values ('Stephen Sommers', 'R', 'Adventure', 1396);
insert into Product(title, amount_in_stock, price, year, id) values ('Notting Hill', 5, 22.00, 1999, 1397);
insert into Movie(director, rating, genre, pid) values ('Roger Mitchell', 'PG-13', 'Romantic Comedy', 1397);
insert into Product(title, amount_in_stock, price, year, id) values ('The World Is Not Enough', 5, 18.00, 1999, 1398);
insert into Movie(director, rating, genre, pid) values ('Michael Apted', 'PG-13', 'Action', 1398);
insert into Product(title, amount_in_stock, price, year, id) values ('American Beauty', 5, 15.00, 1999, 1399);
insert into Movie(director, rating, genre, pid) values ('Sam Mendes', 'R', 'Drama', 1399);
insert into Product(title, amount_in_stock, price, year, id) values ('Austin Powers: The Spy Who Shagged Me', 5, 19.00, 1999, 1400);
insert into Movie(director, rating, genre, pid) values ('Jay Roach', 'PG-13', 'Comedy', 1400);
