--insert into Product(title, amount_in_stock, price, year, id) values ('Title', Quantity, Price, Year, 1195);
--insert into Music(artist, producer, genre, pid) values ('Artist', 'Producer', 'Genre', 1195);
insert into Product(title, amount_in_stock, price, year, id) values ('Their Greatest Hits (1971-1975)', 1, 13.00, 1976, 1196);
insert into Music(artist, producer, genre, pid) values ('Eagles', 'Glyn Johns', 'Rock', 1196);
insert into Product(title, amount_in_stock, price, year, id) values ('Thriller', 5, 15.00, 1982, 1197);
insert into Music(artist, producer, genre, pid) values ('Michael Jackson', 'Michael Jackson', 'Pop', 1197);
insert into Product(title, amount_in_stock, price, year, id) values ('The Wall', 5, 15.00, 1979, 1198);
insert into Music(artist, producer, genre, pid) values ('Pink Floyd', 'Bob Ezrin', 'Pop', 1198);
insert into Product(title, amount_in_stock, price, year, id) values ('Led Zeppelin IV', 2, 14.00, 1971, 1199);
insert into Music(artist, producer, genre, pid) values ('Led Zeppelin', 'Jimmy Page', 'Pop', 1199);
insert into Product(title, amount_in_stock, price, year, id) values ('Back in Black', 5, 19.00, 1980, 1200);
insert into Music(artist, producer, genre, pid) values ('AC/DC', 'Robert John “Mutt” Lange', 'Rock', 1200);
insert into Product(title, amount_in_stock, price, year, id) values ('Double Live', 1, 18.00, 1998, 1201);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Pop', 1201);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits, Vols. 1 & 2', 4, 17.00, 1985, 1202);
insert into Music(artist, producer, genre, pid) values ('Billy Joel', 'Phil Ramone', 'Pop', 1202);
insert into Product(title, amount_in_stock, price, year, id) values ('Come on Over', 1, 16.00, 1997, 1203);
insert into Music(artist, producer, genre, pid) values ('Shania Twain', 'Robert John “Mutt” Lange', 'Pop', 1203);
insert into Product(title, amount_in_stock, price, year, id) values ('Rumours', 5, 13.00, 1977, 1204);
insert into Music(artist, producer, genre, pid) values ('Fleetwood Mac', 'Fleetwood Mac', 'Pop', 1204);
insert into Product(title, amount_in_stock, price, year, id) values ('The Beatles (White Album)', 1, 18.00, 1968, 1205);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Pop', 1205);
insert into Product(title, amount_in_stock, price, year, id) values ('Appetite for Destruction', 3, 18.00, 1987, 1206);
insert into Music(artist, producer, genre, pid) values ('Guns N Roses', 'Mike Clink', 'Pop', 1206);
insert into Product(title, amount_in_stock, price, year, id) values ('Boston', 1, 20.00, 1976, 1207);
insert into Music(artist, producer, genre, pid) values ('Boston', 'John Boylan', 'Pop', 1207);
insert into Product(title, amount_in_stock, price, year, id) values ('The Bodyguard', 3, 13.00, 1992, 1208);
insert into Music(artist, producer, genre, pid) values ('Whitney Houston', 'Whitney Houston', 'Pop', 1208);
insert into Product(title, amount_in_stock, price, year, id) values ('No Fences', 1, 14.00, 1990, 1209);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Pop', 1209);
insert into Product(title, amount_in_stock, price, year, id) values ('1967–1970', 5, 12.00, 1973, 1210);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Rock', 1210);
insert into Product(title, amount_in_stock, price, year, id) values ('Cracked Rear View', 5, 19.00, 1994, 1211);
insert into Music(artist, producer, genre, pid) values ('Hootie and the Blowfish', 'Gloria Gabriel', 'Rock', 1211);
insert into Product(title, amount_in_stock, price, year, id) values ('Physical Graffiti', 5, 18.00, 1975, 1212);
insert into Music(artist, producer, genre, pid) values ('Led Zeppelin', 'Jimmy Page', 'Pop', 1212);
insert into Product(title, amount_in_stock, price, year, id) values ('Hotel California', 3, 18.00, 1976, 1213);
insert into Music(artist, producer, genre, pid) values ('Eagles', 'Bill Szymczyk', 'Rock', 1213);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 1, 15.00, 1974, 1214);
insert into Music(artist, producer, genre, pid) values ('Elton John', 'Gus Dudgeon', 'Pop', 1214);
insert into Product(title, amount_in_stock, price, year, id) values ('Jagged Little Pill', 4, 14.00, 1995, 1215);
insert into Music(artist, producer, genre, pid) values ('Alanis Morissette', 'Glenn Ballard', 'Rock', 1215);
insert into Product(title, amount_in_stock, price, year, id) values ('1962–1966', 2, 17.00, 1973, 1216);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Pop', 1216);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 3, 18.00, 1988, 1217);
insert into Music(artist, producer, genre, pid) values ('Journey', 'Gloria Gabriel', 'Rock', 1217);
insert into Product(title, amount_in_stock, price, year, id) values ('The Dark Side of the Moon', 1, 14.00, 1973, 1218);
insert into Music(artist, producer, genre, pid) values ('Pink Floyd (1998)', 'Jimmy Page', 'Pop', 1218);
insert into Product(title, amount_in_stock, price, year, id) values ('Saturday Night Fever', 1, 17.00, 1977, 1219);
insert into Music(artist, producer, genre, pid) values ('Bee Gees and others', 'Arif Mardin', 'Pop', 1219);
insert into Product(title, amount_in_stock, price, year, id) values ('Born in the U.S.A.', 4, 12.00, 1984, 1220);
insert into Music(artist, producer, genre, pid) values ('Bruce Springsteen', 'Jon Landau', 'Rock', 1220);
insert into Product(title, amount_in_stock, price, year, id) values ('Supernatural', 4, 13.00, 1999, 1221);
insert into Music(artist, producer, genre, pid) values ('Santana', 'Clive Davis', 'Pop', 1221);
insert into Product(title, amount_in_stock, price, year, id) values ('Ropin the Wind', 4, 20.00, 1991, 1222);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Pop', 1222);
insert into Product(title, amount_in_stock, price, year, id) values ('Bat Out of Hell', 3, 17.00, 1977, 1223);
insert into Music(artist, producer, genre, pid) values ('Meat Loaf', 'Todd Rundgren', 'Pop', 1223);
insert into Product(title, amount_in_stock, price, year, id) values ('Backstreet Boys', 4, 13.00, 1997, 1224);
insert into Music(artist, producer, genre, pid) values ('Backstreet Boys', 'Denniz PoP', 'Pop', 1224);
insert into Product(title, amount_in_stock, price, year, id) values ('...Baby One More Time', 4, 15.00, 1999, 1225);
insert into Music(artist, producer, genre, pid) values ('Britney Spears', 'Max Martin', 'Pop', 1225);
insert into Product(title, amount_in_stock, price, year, id) values ('Metallica', 4, 18.00, 1991, 1226);
insert into Music(artist, producer, genre, pid) values ('Metallica', 'Bob Rock', 'Pop', 1226);
insert into Product(title, amount_in_stock, price, year, id) values ('Simon and Garfunkels Greatest Hits', 3, 15.00, 1972, 1227);
insert into Music(artist, producer, genre, pid) values ('Simon & Garfunkel', '', 'Pop', 1227);
insert into Product(title, amount_in_stock, price, year, id) values ('Purple Rain', 4, 14.00, 1984, 1228);
insert into Music(artist, producer, genre, pid) values ('Prince', 'Prince and the Revolution', 'Pop', 1228);
insert into Product(title, amount_in_stock, price, year, id) values ('Whitney Houston', 5, 16.00, 1985, 1229);
insert into Music(artist, producer, genre, pid) values ('Whitney Houston', 'Jermaine Jackson', 'Pop', 1229);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits (1974–1978)', 3, 20.00, 1978, 1230);
insert into Music(artist, producer, genre, pid) values ('Steve Miller Band', 'Steve Miller', 'Rock', 1230);
insert into Product(title, amount_in_stock, price, year, id) values ('Live/1975-85', 4, 18.00, 1986, 1231);
insert into Music(artist, producer, genre, pid) values ('Bruce Springsteen', 'Jon Landau', 'Rock', 1231);
insert into Product(title, amount_in_stock, price, year, id) values ('Millennium', 2, 17.00, 1999, 1232);
insert into Music(artist, producer, genre, pid) values ('Backstreet Boys', 'Max Martin', 'Pop', 1232);
insert into Product(title, amount_in_stock, price, year, id) values ('Ten', 2, 16.00, 1991, 1233);
insert into Music(artist, producer, genre, pid) values ('Pearl Jam', 'Rick Parashar', 'Rock', 1233);
insert into Product(title, amount_in_stock, price, year, id) values ('Yourself or Someone Like You', 5, 18.00, 1996, 1234);
insert into Music(artist, producer, genre, pid) values ('Matchbox Twenty', 'Matt Serletic', 'Pop', 1234);
insert into Product(title, amount_in_stock, price, year, id) values ('No Jacket Required', 3, 18.00, 1985, 1235);
insert into Music(artist, producer, genre, pid) values ('Phil Collins', 'Phil Collins', 'Rock', 1235);
insert into Product(title, amount_in_stock, price, year, id) values ('II', 1, 20.00, 1994, 1236);
insert into Music(artist, producer, genre, pid) values ('Boyz II Men', 'Babyface', 'Pop', 1236);
insert into Product(title, amount_in_stock, price, year, id) values ('Abbey Road', 3, 13.00, 1969, 1237);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Rock', 1237);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 3, 20.00, 1980, 1238);
insert into Music(artist, producer, genre, pid) values ('Kenny Rogers', 'Kenny Rogers', 'Pop', 1238);
insert into Product(title, amount_in_stock, price, year, id) values ('Forrest Gump', 4, 16.00, 1994, 1239);
insert into Music(artist, producer, genre, pid) values ('Various Artists', 'Forrest Gump', 'Pop', 1239);
insert into Product(title, amount_in_stock, price, year, id) values ('Hot Rocks, 1964–1971', 3, 14.00, 1972, 1240);
insert into Music(artist, producer, genre, pid) values ('The Rolling Stones', 'Andrew Loog Oldham', 'Rock', 1240);
insert into Product(title, amount_in_stock, price, year, id) values ('Wide Open Spaces', 3, 17.00, 1998, 1241);
insert into Music(artist, producer, genre, pid) values ('Dixie Chicks', 'Robert John “Mutt” Lange', 'Country', 1241);
insert into Product(title, amount_in_stock, price, year, id) values ('Hysteria', 5, 16.00, 1987, 1242);
insert into Music(artist, producer, genre, pid) values ('Def Leppard', 'Bruce Fairbaim', 'Pop', 1242);
insert into Product(title, amount_in_stock, price, year, id) values ('Slippery When Wet', 5, 16.00, 1986, 1243);
insert into Music(artist, producer, genre, pid) values ('Bon Jovi', 'Kemmy G', 'Pop', 1243);
insert into Product(title, amount_in_stock, price, year, id) values ('Breathless', 3, 16.00, 1992, 1244);
insert into Music(artist, producer, genre, pid) values ('Kenny G', 'Robert John “Mutt” Lange', 'Pop', 1244);
insert into Product(title, amount_in_stock, price, year, id) values ('The Woman in Me', 4, 14.00, 1995, 1245);
insert into Music(artist, producer, genre, pid) values ('Shania Twain', 'Robert John “Mutt” Lange', 'Pop', 1245);
insert into Product(title, amount_in_stock, price, year, id) values ('Pieces of You', 2, 16.00, 1995, 1246);
insert into Music(artist, producer, genre, pid) values ('Jewel', 'Ben Keit', 'Pop', 1246);
insert into Product(title, amount_in_stock, price, year, id) values ('Led Zeppelin II', 4, 12.00, 1969, 1247);
insert into Music(artist, producer, genre, pid) values ('Led Zeppelin', 'Jimmy Page', 'Pop', 1247);
insert into Product(title, amount_in_stock, price, year, id) values ('Up!', 4, 17.00, 2002, 1248);
insert into Music(artist, producer, genre, pid) values ('Shania Twain', 'Robert John “Mutt” Lange', 'Country', 1248);
insert into Product(title, amount_in_stock, price, year, id) values ('No Strings Attached', 1, 13.00, 2000, 1249);
insert into Music(artist, producer, genre, pid) values ('*NSYNC', 'Jermaine Jackson', 'Pop', 1249);
insert into Product(title, amount_in_stock, price, year, id) values ('Human Clay', 3, 14.00, 1999, 1250);
insert into Music(artist, producer, genre, pid) values ('Creed', 'John Kurzweg', 'Rock', 1250);
insert into Product(title, amount_in_stock, price, year, id) values ('Sgt. Peppers Lonely Hearts Club Band', 5, 20.00, 1967, 1251);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Rock', 1251);
insert into Product(title, amount_in_stock, price, year, id) values ('Devil Without a Cause', 1, 14.00, 1998, 1252);
insert into Music(artist, producer, genre, pid) values ('Kid Rock', 'Kid Rock', 'Pop', 1252);
insert into Product(title, amount_in_stock, price, year, id) values ('Falling Into You', 3, 17.00, 1996, 1253);
insert into Music(artist, producer, genre, pid) values ('Celine Dion', 'Babyface', 'Country', 1253);
insert into Product(title, amount_in_stock, price, year, id) values ('Houses of the Holy', 2, 16.00, 1973, 1254);
insert into Music(artist, producer, genre, pid) values ('Led Zeppelin', 'Jimmy Page', 'Pop', 1254);
insert into Product(title, amount_in_stock, price, year, id) values ('Speakerboxxx/The Love Below', 2, 18.00, 2003, 1255);
insert into Music(artist, producer, genre, pid) values ('Outkast', 'Andre 3000', 'Rock', 1255);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 2, 17.00, 1976, 1256);
insert into Music(artist, producer, genre, pid) values ('James Taylor', 'Peter Asher', 'Pop', 1256);
insert into Product(title, amount_in_stock, price, year, id) values ('Eagles Greatest Hits, Vol. 2', 3, 13.00, 1982, 1257);
insert into Music(artist, producer, genre, pid) values ('Eagles', 'Bill Szymczyk', 'Rock', 1257);
insert into Product(title, amount_in_stock, price, year, id) values ('CrazySexyCool', 1, 16.00, 1994, 1258);
insert into Music(artist, producer, genre, pid) values ('TLC', 'Dallas Austin', 'Pop', 1258);
insert into Product(title, amount_in_stock, price, year, id) values ('Dirty Dancing', 3, 14.00, 1987, 1259);
insert into Music(artist, producer, genre, pid) values ('Soundtrack', 'RCA', 'Pop', 1259);
insert into Product(title, amount_in_stock, price, year, id) values ('Titanic', 3, 19.00, 1997, 1260);
insert into Music(artist, producer, genre, pid) values ('Various Artists', 'Sony', 'Rock', 1260);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 3, 20.00, 1980, 1261);
insert into Music(artist, producer, genre, pid) values ('Aerosmith', 'Various', 'Pop', 1261);
insert into Product(title, amount_in_stock, price, year, id) values ('Faith', 5, 15.00, 1987, 1262);
insert into Music(artist, producer, genre, pid) values ('George Michael', 'George Michael', 'Pop', 1262);
insert into Product(title, amount_in_stock, price, year, id) values ('Legend', 5, 16.00, 1984, 1263);
insert into Music(artist, producer, genre, pid) values ('Bob Marley & The Wailers', 'Bob Marley', 'Pop', 1263);
insert into Product(title, amount_in_stock, price, year, id) values ('Pyromania', 4, 13.00, 1983, 1264);
insert into Music(artist, producer, genre, pid) values ('Def Leppard', 'Robert John “Mutt” Lange', 'Pop', 1264);
insert into Product(title, amount_in_stock, price, year, id) values ('The Stranger', 4, 19.00, 1977, 1265);
insert into Music(artist, producer, genre, pid) values ('Billy Joel', 'Phil Ramone', 'Pop', 1265);
insert into Product(title, amount_in_stock, price, year, id) values ('Come Away With Me', 5, 16.00, 2002, 1266);
insert into Music(artist, producer, genre, pid) values ('Norah Jones', 'Norah Jones', 'Pop', 1266);
insert into Product(title, amount_in_stock, price, year, id) values ('Please Hammer Dont Hurt Em', 3, 12.00, 1990, 1267);
insert into Music(artist, producer, genre, pid) values ('MC Hammer', 'MC Hammer', 'Pop', 1267);
insert into Product(title, amount_in_stock, price, year, id) values ('Patsy Clines Greatest Hits', 4, 12.00, 1967, 1268);
insert into Music(artist, producer, genre, pid) values ('Patsy Cline', 'Owen Bradley', 'Pop', 1268);
insert into Product(title, amount_in_stock, price, year, id) values ('Unplugged', 2, 13.00, 1992, 1269);
insert into Music(artist, producer, genre, pid) values ('Eric Clapton', 'Russ Titelman', 'Pop', 1269);
insert into Product(title, amount_in_stock, price, year, id) values ('Lets Talk About Love', 5, 14.00, 1997, 1270);
insert into Music(artist, producer, genre, pid) values ('Celine Dion', 'Walter Afanasieff', 'Country', 1270);
insert into Product(title, amount_in_stock, price, year, id) values ('Fly', 1, 20.00, 1999, 1271);
insert into Music(artist, producer, genre, pid) values ('Dixie Chicks', 'Dixie Chicks', 'Country', 1271);
insert into Product(title, amount_in_stock, price, year, id) values ('Best of The Doobies', 4, 15.00, 1976, 1272);
insert into Music(artist, producer, genre, pid) values ('Doobie Brothers', 'Ted Templeman', 'Pop', 1272);
insert into Product(title, amount_in_stock, price, year, id) values ('Led Zeppelin', 5, 16.00, 1990, 1273);
insert into Music(artist, producer, genre, pid) values ('Led Zeppelin', 'Jimmy Page', 'Rock', 1273);
insert into Product(title, amount_in_stock, price, year, id) values ('Hybrid Theory', 4, 19.00, 2000, 1274);
insert into Music(artist, producer, genre, pid) values ('Linkin Park', 'Don Gilmore', 'Pop', 1274);
insert into Product(title, amount_in_stock, price, year, id) values ('Greatest Hits', 3, 15.00, 1993, 1275);
insert into Music(artist, producer, genre, pid) values ('Tom Petty and the Heartbreakers', 'Mike Campbell', 'Rock', 1275);
insert into Product(title, amount_in_stock, price, year, id) values ('Tragic Kingdom', 4, 13.00, 1995, 1276);
insert into Music(artist, producer, genre, pid) values ('No Doubt', 'Matthew Wilder', 'Pop', 1276);
insert into Product(title, amount_in_stock, price, year, id) values ('Dookie', 5, 20.00, 1994, 1277);
insert into Music(artist, producer, genre, pid) values ('Green Day', 'Rob Cavallo', 'Rock', 1277);
insert into Product(title, amount_in_stock, price, year, id) values ('Nevermind', 4, 14.00, 1991, 1278);
insert into Music(artist, producer, genre, pid) values ('Nirvana', 'Butch Vig', 'Pop', 1278);
insert into Product(title, amount_in_stock, price, year, id) values ('The Immaculate Collection', 1, 19.00, 1990, 1279);
insert into Music(artist, producer, genre, pid) values ('Madonna', 'Madonna', 'Pop', 1279);
insert into Product(title, amount_in_stock, price, year, id) values ('Like a Virgin', 4, 18.00, 1984, 1280);
insert into Music(artist, producer, genre, pid) values ('Madonna', 'Nile Rodgers', 'Rock', 1280);
insert into Product(title, amount_in_stock, price, year, id) values ('Tapestry', 5, 14.00, 1971, 1281);
insert into Music(artist, producer, genre, pid) values ('Carole King', 'Lou Adler', 'Pop', 1281);
insert into Product(title, amount_in_stock, price, year, id) values ('Cant Slow Down', 1, 14.00, 1983, 1282);
insert into Music(artist, producer, genre, pid) values ('Lionel Richie', 'Lionel Richie', 'Pop', 1282);
insert into Product(title, amount_in_stock, price, year, id) values ('*NSYNC', 3, 18.00, 1998, 1283);
insert into Music(artist, producer, genre, pid) values ('*NSYNC', 'Johnny Wright', 'Pop', 1283);
insert into Product(title, amount_in_stock, price, year, id) values ('The Best of The Doors', 3, 14.00, 1985, 1284);
insert into Music(artist, producer, genre, pid) values ('The Doors', 'Paul Rothchild', 'Pop', 1284);
insert into Product(title, amount_in_stock, price, year, id) values ('Life After Death', 4, 15.00, 1997, 1285);
insert into Music(artist, producer, genre, pid) values ('The Notorious B.I.G.', 'Sean “Puffy” Combs', 'Pop', 1285);
insert into Product(title, amount_in_stock, price, year, id) values ('The Lion King', 3, 14.00, 1994, 1286);
insert into Music(artist, producer, genre, pid) values ('Soundtrack', 'Hans Zimmer', 'Pop', 1286);
insert into Product(title, amount_in_stock, price, year, id) values ('Eliminator', 3, 15.00, 1983, 1287);
insert into Music(artist, producer, genre, pid) values ('ZZ Top', 'Bill Ham', 'Pop', 1287);
insert into Product(title, amount_in_stock, price, year, id) values ('Oops!… I Did It Again', 4, 13.00, 2000, 1288);
insert into Music(artist, producer, genre, pid) values ('Britney Spears', 'Max Martin', 'Pop', 1288);
insert into Product(title, amount_in_stock, price, year, id) values ('The Joshua Tree', 1, 20.00, 1987, 1289);
insert into Music(artist, producer, genre, pid) values ('U2', 'Brian Eno', 'Pop', 1289);
insert into Product(title, amount_in_stock, price, year, id) values ('Music Box', 2, 14.00, 1993, 1290);
insert into Music(artist, producer, genre, pid) values ('Mariah Carey', 'Mariah Carey', 'Rock', 1290);
insert into Product(title, amount_in_stock, price, year, id) values ('Garth Brooks', 3, 12.00, 1989, 1291);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Rock', 1291);
insert into Product(title, amount_in_stock, price, year, id) values ('Van Halen', 1, 19.00, 1978, 1292);
insert into Music(artist, producer, genre, pid) values ('Van Halen', 'Ted Templeman', 'Pop', 1292);
insert into Product(title, amount_in_stock, price, year, id) values ('Confessions', 4, 17.00, 2004, 1293);
insert into Music(artist, producer, genre, pid) values ('Usher', 'Jermaine Dupri', 'Rock', 1293);
insert into Product(title, amount_in_stock, price, year, id) values ('Daydream', 4, 20.00, 1995, 1294);
insert into Music(artist, producer, genre, pid) values ('Mariah Carey', 'Mariah Carey', 'Pop', 1294);
insert into Product(title, amount_in_stock, price, year, id) values ('Songs in the Key of Life', 2, 19.00, 1976, 1295);
insert into Music(artist, producer, genre, pid) values ('Stevie Wonder', 'Stevie Wonder', 'Rock', 1295);
insert into Product(title, amount_in_stock, price, year, id) values ('Sevens', 2, 12.00, 1997, 1296);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Country', 1296);
insert into Product(title, amount_in_stock, price, year, id) values ('The Hits', 3, 17.00, 1994, 1297);
insert into Music(artist, producer, genre, pid) values ('Garth Brooks', 'Allen Reynolds', 'Country', 1297);
insert into Product(title, amount_in_stock, price, year, id) values ('1984 (MCMLXXXIV)', 3, 18.00, 1984, 1298);
insert into Music(artist, producer, genre, pid) values ('Van Halen', 'Ted Templeman', 'Rock', 1298);
insert into Product(title, amount_in_stock, price, year, id) values ('1', 1, 16.00, 2000, 1299);
insert into Music(artist, producer, genre, pid) values ('The Beatles', 'George Martin', 'Pop', 1299);
